### ISSUE TITLE
download_button_html looks weird with long form titles

### ISSUE THREAD

**Issue by nonprofittechy** [SuffolkLITLab/docassemble-AssemblyLine#186]
![image](https://user-images.githubusercontent.com/7645641/121445757-19185300-c960-11eb-9c88-e1b6dc3daf99.png)

**Comment by purplesky2016** [comment]
Maybe we can force the Title column to be narrower. One option is to add some class name in the table, then add css rules for them. For example, split the Title/Button columns to be 30%/70%, so that the buttons will have enough space to stay horizontal.

Here is the mobile version.

![image](https://user-images.githubusercontent.com/20231649/123700973-3473d100-d82f-11eb-8376-3826b1849c91.png)

**Comment by nonprofittechy** [comment]
I like this--simple solution that seems worth implementing

**Comment by purplesky2016** [comment]
Even better, I can use the existing class names to do it!
