### ISSUE TITLE
Make the "next" button wider

### ISSUE THREAD

**Issue by nonprofittechy** [SuffolkLITLab/docassemble-AssemblyLine#210]
In current user testing of https://github.com/nonprofittechy/docassemble-HousingCodeChecklist persistent feedback is that the next button is hard to interact with. Just a little extra left and right margin should help for this specific button. Perhaps best option would be a minimum width?

**Comment by nonprofittechy** [comment]
```
.btn {
  min-width: 8em;
}
```

**Comment by nonprofittechy** [comment]
![image](https://user-images.githubusercontent.com/7645641/123665128-fadaa000-d805-11eb-9dd3-938ffebeebad.png)

Pay attention to the download screen buttons--maybe we want to make those a little narrower.

**Comment by purplesky2016** [comment]
@plocket made some css changes for the download screen to **horizontally** align the buttons on **mobile** awhile ago, and they contain .btn. This new rule seems to be overriding those rules, therefore you get the vertical button lineup as shown in the above image. 

We could either apply this new rule to large screens only, so that we preserve the effect of @plocket's changes:

```
@media only screen and (min-width: 450px) {
  .btn {
    min-width: 8rem;
  }
}
```
Or we specifically address just the Next button using a different selector, which has no effect on the download screen:
```
.btn[type='submit'] {
  min-width: 8rem;
}
```

**Comment by purplesky2016** [comment]
A related question: should we use `em `or `rem`? Does it matter in DA? Right now both are used in our styles. 

> em is relative to the font-size of its direct or nearest parent, rem is only relative to the html (root) font-size.

**Comment by nonprofittechy** [comment]
Focusing on just the submit buttons is reasonable. Would that also work on yes/no buttons for a `datatype: yesno` question?

Personally I did not know about `rem`. I don't have an opinion but @plocket might

**Comment by purplesky2016** [comment]
Well, the checkbox for `datatype: yesno` is actually an image, not a real `button` so I'm not sure if we can style it or not. I'll play with it and see if we have any luck.

**Comment by nonprofittechy** [comment]
I mean the button that replaces "Next", not the inline version. Styling .btn definitely changes the yes/no.

**Comment by plocket** [comment]
`yesnomaybe:` buttons are all `[type='submit']`, so that should work. We might want to continue to think about what kinds of buttons we want to change and what kind we don't. Sometimes da just doesn't have the specificity that would allow us to be too picky, but sometimes there are things we can do.

As far as excluding the download page buttons, I suggest avoiding the method above. We can use more specific selectors that will target those buttons instead as long as this new css doesn't do anything crazy. For example, we want to avoid `!important`.

**Comment by plocket** [comment]
> A related question: should we use em or rem? Does it matter in DA? Right now both are used in our styles.

Maybe we can make a separate issue for this?

**Comment by purplesky2016** [comment]
@nonprofittechy - could you post an image of the `yes/no` button widened by the new btn. rule?

Maybe I am missing something obvious. When I tried btn. it din't effect `yesno `nor `yesnomaybe`. Inspection shows that they are `fieldset`.

**Comment by nonprofittechy** [comment]
![image](https://user-images.githubusercontent.com/7645641/124005395-04e7d480-d9a7-11eb-9b50-41512556b7f2.png)

I ended up doing just .btn-primary and .btn-secondary (secondary is needed to set the state when someone clicks and it briefly turns grey)

```
.btn-primary {
  min-width: 8em;
}

.btn-secondary {
  min-width: 8em;
}
```

**Comment by purplesky2016** [comment]
I see, the image shows two regular buttons labeled Yes and No, not a real `datatype: yesno` question. That explains.

**Comment by purplesky2016** [comment]
I played with the radio button and checkbox, here is one way to make a difference, just not sure if it's worth the trouble because the label size is not easy to sync with the image size. (Left=modified, right=original)
![image](https://user-images.githubusercontent.com/20231649/124010461-d66cf800-d9ac-11eb-8b69-a4563ab6e4c6.png)

**Comment by purplesky2016** [comment]
Looks like `.btn[type='submit']` is sufficient for our issue, I push the code.
