### ISSUE TITLE
Add support for a `.title` or possibly `.prefix` attribute of an ALIndividual

### ISSUE THREAD

**Issue by nonprofittechy** [SuffolkLITLab/docassemble-AssemblyLine#242]
This should also extend the `name_fields()` method appropriately, and come with an internationalizable list of appropriate titles, such as Dr., Judge, etc.

This might be a place to start: https://en.wikipedia.org/wiki/English_honorifics

Note that honorifics vary from language to language. They are not always an optional part of a person's name. The full list on Wikipedia is probably excessive!

The use case I am thinking of is naming a specialist who will provide a service ordered by an administrative agency or court. So professional titles are most important. If the list we provide by default exceeds 5-10, it won't be useful.

**Comment by BryceStevenWilley** [comment]
I just checked this because I was curious what ECF says about it (it allows prefixes in names too). But Tyler seems to think most professional titles are suffixes instead of prefixes.  For example, here's the list that the Adams county takes:

* II
* III
* IV
* V
* VI
* Sr
* Jr
* RN
* PhD
* MSW
* MD
* MA
* LPN
* LPA
* JD
* Esq
* DVM
* DO
* DDS
* DC
* CPA

I don't think that way is really thought through well (what happens if Curtis Jones, III is also a PhD?), but it might help to think of the titles like these more specific professional titles (PhD and MD as opposed to just Dr.)

**Comment by nonprofittechy** [comment]
"prefix" is probably a better term than "title". The ones listed above from Tyler's list do tend to be suffixes and not prefixes--E.g., we might have Dr. John Jones, PhD--not PhD John Jones.

That does make me realize that just adding some more suffixes might be a really good start at this problem though. I'm happy to start by matching Tyler's list of suffixes.

This is definitely a place where UK standard English differs quite a lot from American conventions. Here it's not unusual to drop the prefix, but in the UK I think titles are very much part of someone's name in most forms of address other than very informal.

**Comment by nonprofittechy** [comment]
Duplicate of #208
