### ISSUE TITLE
Move the ALKiln trigger variable code out of the styled package

### ISSUE THREAD

**Issue by plocket** [SuffolkLITLab/docassemble-AssemblyLine#355]
https://github.com/SuffolkLITLab/docassemble-AssemblyLine/blob/be4a8dd51ccf12b8e3ca4e8821b8e78c97353334/docassemble/AssemblyLine/data/questions/al_visual.yml#L51-L52

This is currently in al_visual.yml, which is excluded from al_package_unstyled.yml. That means that developers that use that unstyled version have to do extra work to set up for ALKiln testing. In addition, this doesn't do anything visual to the interviews.

Is there a better place to put this code?

**Comment by nonprofittechy** [comment]
Not sure of other options to place the code, but I feel pretty sure that the al_package_unstyled.yml shouldn't override any screen parts, especially since `default screen parts` takes precedence over configuration `screen parts` and interview `metadata` tag.

One option would just be to clearly document this as something who wants to use the unstyled code will need to manually add. We could also move this snippet of HTML into a template so it's better encapsulated and can be centrally updated for both the styled/unstyled variations.

**Comment by plocket** [comment]
I like the idea of a template. What file would that live in?

Regarding documentation, it's there already 👍 .

**Comment by nonprofittechy** [comment]
I think the template could go in `al_code.yml`. No strong feelings though--just something that is already included in assembly_line_unstyled.yml would be best.

**Comment by BryceStevenWilley** [comment]
IMO this should remain open. Switching to a template is pretty straight forward, shouldn't break anything existing, and would make using it with unstyled a bit easier. The only thing that makes it take more than 5 minutes is aligning docs, but it's still a small task.

**Comment by nonprofittechy** [comment]
Eh, that's fine. I think this is describing a vanishingly small use case, but I'm fine to let someone else give it a try.

**Comment by nonprofittechy** [comment]
@plocket can we describe why the trigger variable is still needed, and are there any other upstream options we should push for?

**Comment by BryceStevenWilley** [comment]
I made a quick patch for this. Sorry, I've probably spent more time responding to the issue than it took to just change it. 

The trigger variable is needed because docassemble's encoding of field ids and names on generic objects still uses `x`. So on a generic variable screen, there's nothing in the HTML itself that we can use to determine what `x` is for `x.name.first`, or whatever. I don't think Jonathon would want an upstream fix here;  the slack threads talking about this are archived.

We have additional things that we might add to this template as well, as in https://github.com/SuffolkLITLab/ALKiln/issues/582. I don't think it's something that we can push upstream.

**Comment by plocket** [comment]
Jonathan at some recent point mentioned that he would consider changing some of the stuff to do with `getField()` and its friends to allow js on the page to be able to more easily access fields and values with just their variable names. I haven't seen those changes yet, though.
