### ISSUE TITLE
Make some features (signature, sharing) that depend on multi_user or a valid email/sms config responsive to whether it's turned on or off

### ISSUE THREAD

**Issue by nonprofittechy** [SuffolkLITLab/docassemble-AssemblyLine#411]
I think we might want some Python functions to check for a valid SMS and email configuration.

I think we'll need to audit the default interview text to look for places we offer the ability to send by email or SMS and conditionally turn those off. In most places we allow both methods, and in some there's a backup method of clicking a link to copy text, so we probably don't want to turn these totally off in the footer.

**Comment by BryceStevenWilley** [comment]
I've made some progress on hiding SMS specific options downstream in MLH on just the Share page, trying to get it upstream now.

The places where I see we offer SMS sending that I've address in my branch:

* [x] [In the Share page](https://github.com/SuffolkLITLab/docassemble-AssemblyLine/blob/5da76ddeaff65634a61449e5f04b3f41f490ae31/docassemble/AssemblyLine/data/questions/al_visual.yml#L202)
* [ ] [In the reminder system](https://github.com/SuffolkLITLab/docassemble-AssemblyLine/blob/5da76ddeaff65634a61449e5f04b3f41f490ae31/docassemble/AssemblyLine/data/questions/al_reminders.yml#L69)
* [ ] [the option to text the signature](https://github.com/SuffolkLITLab/docassemble-AssemblyLine/blob/5da76ddeaff65634a61449e5f04b3f41f490ae31/docassemble/AssemblyLine/data/questions/al_code.yml#L141)

I'm gonna focus on just those at the moment, since the email stuff seems to be in more places and more critical to running a DA server (with password resets, etc.)

**Comment by BryceStevenWilley** [comment]
Reopening, as I didn't cover things that have `multi_user = False` yet. I feel like there are a few approaches we could take to those interviews:

* turn things off entirely
* give users the ability to manually turn it on and off
* automatically turn it on when some one shares the signature screen, and turns it off once the form is signed (or some other type of control)

**Comment by nonprofittechy** [comment]
> Reopening, as I didn't cover things that have `multi_user = False` yet. I feel like there are a few approaches we could take to those interviews:
> 
>     * turn things off entirely
> 
>     * give users the ability to manually turn it on and off
> 
>     * automatically turn it on when some one shares the signature screen, and turns it off once the form is signed (or some other type of control)

I think we'll want to go with your first idea, turn sharing off entirely when `multi_user=False`. This is because it will usually only be the case when the author has to follow some data privacy liability standard, such as storing PII like a social security number or bank account number. Likely they'll have their data controls in a written policy that they have to maintain and certify that they're following. Making it up to the user to turn off doesn't sound like a good idea.

For signature to your phone, it would still work if the user is logged in, it's just a pain to use in that scenario.
