### ISSUE TITLE
Research needs around generating accessible "tagged" PDFs

### ISSUE THREAD

**Issue by nonprofittechy** [SuffolkLITLab/docassemble-AssemblyLine#422]
This might be built-in to Docassemble; we might need to tag the attachment block somehow. This might belong to the Weaver or as a documentation item

**Comment by BryceStevenWilley** [comment]
I don't think this is built into docassemble (unless we're generating PDFs from markdown, and even then it might not be), since accessibility in PDFs seems to be more complicated the more I look into it (https://www.section508.gov/create/pdfs/ is a good starting point). It's closer to web accessibility where we not only need content accessibility like alt text but also we need to delineate the whole PDF with additional markup-like tags, kinda like ARIA. I'd be curious if we can get 75% of the way there with pdfminer splitting up paragraphs and lines.

**Comment by nonprofittechy** [comment]
I was thinking specifically about the "tagged pdf" modifier for DOCX templates

https://docassemble.org/docs/initial.html#tagged%20pdf

**Comment by BryceStevenWilley** [comment]
Sorry, was thinking mostly of having a PDF as the starting template. 

The `tagged pdf` option does look useful. The most I can find about what exactly it does is that it just uses libreoffice's tagged pdf option, which "includes special tags into the corresponding PDF tags. Some tags that are exported are table of contents, hyperlinks, and controls. This option can increase file sizes significantly." It might be enough, but we should confirm.

**Comment by BryceStevenWilley** [comment]
This wouldn't be a thing that we could do in AL itself, but during the starting process of labeling a PDF, [A2J's best practice guide for accessible PDFs](https://www.a2jauthor.org/content/best-practices-guide-creating-accessible-pdf-templates) is useful.

**Comment by nonprofittechy** [comment]
Fixed in the Weaver in https://github.com/SuffolkLITLab/docassemble-ALWeaver/pull/835
