### ISSUE TITLE
Remove name change questions from ALCore

### ISSUE THREAD

**Issue by BryceStevenWilley** [SuffolkLITLab/docassemble-AssemblyLine#677]
Was about to make a new release of Assembly Line, but remembered https://github.com/SuffolkLITLab/docassemble-AssemblyLine/pull/668. I know we made some quick changes to this package and the Weaver for LITCon, but IMO this isn't a good addition to AL core, and we should rethink it more before making a release.

Some options I remember discussing with @nonprofittechy:
* I am wrong, and it's fine to add subject matter specific questions to the question library. No changes necessary
* We move the name change specific questions to a different YAML file, either `ql_subject_matter_specific.yml` or `ql_name_change.yml`. Additional subject matter questions go in similar files.
* we make subject matter specific packages, like `ALNameChange` that holds these specific questions. Folks making a name change for California would include `california_organization.yml` and `al_name_change.yml`, making the few small changes they need or want.
* We expand the idea of the question library to include questions that the weaver knows about, and can add to newly weaved forms directly. The questions only live in those specific packages at runtime.

**Comment by nonprofittechy** [comment]
I'd lean to leaving those questions in for now. They're a little niche but they're not slowing down anyone's interviews. If I remember right it's basically 2 questions you're thinking of removing? The general purpose "preferred name" and "aliases" should be left in, so it's just the ones about getting parental consent.

That said it's no big deal to remove them since we didn't make a hullabaloo about making any of the forms go live.

Long term, I think the subject matter specific package in the Weaver is probably the way to go.

**Comment by BryceStevenWilley** [comment]
> They're a little niche but they're not slowing down anyone's interviews

True, they aren't negatively affecting other things, but my main concern is it's hard to remove things once they're in.
* If we eventually want to move them somewhere else, we should take them back out now and move them when we can
* If we keep them in until we want to move them and someone starts using those questions, moving those questions will break their interviews
* If we keep them in, but are assuming that people won't use them because we didn't really announce it, why keep them in?

**Comment by nonprofittechy** [comment]
> If we keep them in, but are assuming that people won't use them because we didn't really announce it, why keep them in?

I have about 90% certainty that nobody is using them right now. But I really have no concern about these 2 extra questions being in the library. Breaking someone's interview (maybe) has a higher risk to me than being something other than fully consistent layout of where we put questions. So that 10% uncertainty is weighing more heavily for me.

I'm also not really sure how soon we'll get around to reengineering the Weaver to handle the flexible library designs. It's a good idea, but we have had that idea for 2 years without making progress on it. So we'd be taking out some slightly useful questions without a clear path to adding back a replacement mechanism for someone to use them on any real timeline.

All that said, I don't think this is very important either way, so I'm fine deferring to your goal as it sounds like you have a strong conviction. We'll just have to be ready for that experience of breaking people's tests from the conference. That should be a pretty small set of users and hopefully they'll reach out if something doesn't work anymore for them so we can explain why.

**Comment by nonprofittechy** [comment]
To make the fix for people whose interviews we might break as small as possible, I suggest we move these to a new question file for now rather than totally deleting them. That can be in its own "name change" package (that we eventually tie into the Weaver) or in the main AssemblyLine package. I can see good reasons for both patterns.

**Comment by BryceStevenWilley** [comment]
> Breaking someone's interview (maybe) has a higher risk to me than being something other than fully consistent layout of where we put questions. So that 10% uncertainty is weighing more heavily for me.

I think I see our main misunderstanding; I'm with you on not breaking someone's interview, but since we hadn't made an official release, I had been assuming that no one was using it yet. Realizing that our recommended way of installing things with the Dashboard does go through GitHub though.

I guess I should have pushed against adding them more, but you're right, it's pretty minor and not worth this long discussion that we've already had, apologies.

I'll close this issue and just leave it.
