### ISSUE TITLE
Discuss: add an optional "message" box to go with the send by email feature

### ISSUE THREAD

**Issue by nonprofittechy** [SuffolkLITLab/docassemble-AssemblyLine#76]
Downside: it's not persistent information. Upside: let people send documents with a little more context.

This could be a parameter to the send_button_html() method of ALDocumentBundle.

**Comment by nonprofittechy** [comment]
We don't think we want this on by default, so we can wait until someone asks for it.

**Comment by BryceStevenWilley** [comment]
Can you expand on the downside? This is something that the user of the interview types into the "Send email" section, so they could send it to a case worker saying "Here's this form we talked about", right? Not sure why it's a downside that it's not persistent. 

Agreed that it should be off by default.

**Comment by nonprofittechy** [comment]
Pinging @plocket as they raised this issue during a Monday call

**Comment by plocket** [comment]
The main downside I see is, as stated, the possible expectation a user could have that their input will be persistent as that's the expectation we've created through the rest of the interview. If the page gets reloaded for some reason - they go to 'Make changes' and back or something - the message will be gone. I'm not sure it's a huge problem.

That reminds me - do we want the message to get erased when the user sends the email? I think it would give the user a sense that the message has been sent.

Other possible feature - provide a list of messages sent and what email they were sent to, though this would also disappear if the page was refreshed unless we can set some variables on the server. Maybe we can do that inside the email-sending action.

**Comment by plocket** [comment]
I agree with the general sentiments there. Also want to note that Google Docs do allow you to see who you've shared with.

**Comment by BryceStevenWilley** [comment]
> If the page gets reloaded for some reason - they go to 'Make changes' and back or something - the message will be gone. 

I don't think that's a huge problem, but a good solution (inspired by Quinten's relation to Google doc's share button) is to just say "Discard unsaved message?". Still transient on one page, don't have to worry about saving it across pages.

![Screenshot from 2021-05-07 09-22-59](https://user-images.githubusercontent.com/6252212/117456262-01d7e700-af16-11eb-8452-19cb0410c45f.png)

> do we want the message to get erased when the user sends the email? I think it would give the user a sense that the message has been sent.

I guess, but that shouldn't be the only indication that the email got sent.

> provide a list of messages sent and what email they were sent to

Snazy and a cool idea, but seems like a bit more work for much less payoff: how many different people with different messages would you want to send that too? Maybe it's just me but I'd be more likely to send it to  myself and then forward it to everyone else later. 

> Also want to note that Google Docs do allow you to see who you've shared with.

True, but that information is persistent, and is probably much easier for Google because the shared contacts see the live form. What would we want to show if the form fields are changed at all, a "you sent an older version to X,Y, and Z" (how would we know that fields have been changed)? Would users expect that "older version" message to be there if they went through the interview again from scratch?

Overall, I understand the original question: warning when the unsent message is a good idea, but I don't think we need to persist anything else really.

**Comment by plocket** [comment]
> "Discard unsaved message?"

Good inspiration. Will have to think how we implement that.

> I guess, but that shouldn't be the only indication that the email got sent.

Sorry if that was the implication. It was definitely not my intention. An explicit message is important. I suspect that clearing the field will help with that feedback and that not clearing the field with be confusing. We can always see if we can do some user research.

> I'd be more likely to send it to myself and then forward it to everyone else later.

I personally would probably send it from the page, not from my email, so maybe we can't make an assumption about this. It feels then like this would need user research and therefore might not be doable. Also, as the edit added, I only imagine this as something discussed in the future, not anything we have to worry about for quite a while.

> "you sent an older version to X,Y, and Z"

I was imaging just putting the date and time that the user last shared, and we could word it to be clear that this list is about this specific interview. Still, something we only need to discuss if we decide to do so at some future time.
