### ISSUE TITLE
Add ALDocument example usage and attribute defaults to class docstring

### ISSUE THREAD

**Issue by plocket** [SuffolkLITLab/docassemble-AssemblyLine#89]
[The original topic of this issue was setting defaults in the class itself. We decided `has_addendum` should have a default and we implemented that. We decided `enabled` should not have a default.

Now this issue has been converted to focus on documenting this class's behavior.]

This would be in the class itself. Ideas for defaults:
- enabled: True
- has_addendum: False

**Comment by nonprofittechy** [comment]
The challenge is that DA does not seek an attribute that is already defined.

**Comment by BryceStevenWilley** [comment]
Alternatives:
1. (I don't like the organization of this one): a generic ALDocument object block that sets both `enabled` and `has_addendum`.
2. Some usage examples in the ALDocument docstring. I.e.:
```
 The "addendum" attribute will typically be handled in a generic object block.
  Multiple documents can use the same addendum template, with just the case caption
  varying.
  
  Required attributes:
    - filename: name used for output PDF
    - title: display name for the output PDF
    - enabled
    - has_addendum: set to False if the document never has overflow, like for a DOCX template
  
  Optional attribute:
    - addendum: an attachment block
    - overflow_fields

Example:
---
objects:
  - my_doc: ALDocument.using(filename="myDoc.pdf", title="myDoc", enabled=True, has_addendum=False)
--- 
attachment:
    variable name: my_doc[i]
    ...
```

**Comment by nonprofittechy** [comment]
I agree that the `generic object` block feels pretty awkward for this use, although it would definitely be possible.

I lean towards adding more documentation. Other thoughts:

1. I think it's reasonable to expect developers to explicitly define "enabled". Many documents are contingent, and the main benefit of using ALDocument is to simplify contingent documents. Forms from the Weaver already have the code generated with the default of enabled.
2. I'm open to ideas on how to make working with `has_addendum` more optional. We could check for the existence of the attribute rather than its value, perhaps. The downside is that means that the attribute would always need to be defined at the same time the object is created or in a mandatory block. I'm not sure that would be a real-world limitation--presumably having the possibility of an addendum is always known at object initialization.

**Comment by plocket** [comment]
I think improved documentation sounds like a great idea regardless of the decision here. Does the docstring show up in the sidebar item? Also, maybe I'm jumping the gun. This could be an issue we can observe over time. When the package is more widely used, we can use this issue to note how often people bring this up and make a decision at that point. That could be really interesting from a user research perspective.

That said, these are some thoughts I had when reading the above.

Defaults:

One option is to add defaults in the module when the objects are initialized, not in the YAML. That makes this functionality a bit more invisible/implicit which isn't my favorite thing, though. Also, I think I must be missing something or one of you would have proposed that already.

(Pseudocode)
```python
class ALDocument():
  init...
    ...
    self.enabled = args.enabled or True
    self. has_addendum = args.has_addendum or False
```

I'd be really interested in hearing more about what makes a `generic object` block more awkward. What comes up for me is the complication of mixing da YAML attribute definitions with code in a module. Are there other things that give it a bad smell? Maybe that can be a Monday or Tuesday conversation.

Thoughts on `enabled`:

Though ALDocument is useful for simplifying contingent documents, it's used for making all documents, not just contingent ones. Most of the interviews I've seen don't have contingent documents. It's a bit of boilerplate and easy to forget/lose. The weaver does help with that initial part until editing mucks things up.

I'm also curious about whether there is a more explicit alternative interface that could ease this pain. I hesitate to give an example as I've found that people focus on troubleshooting the example instead of looking at the intention. I don't see a way around it, though. I'll try to make this example as unusable and as unlikely as possible to try to avoid that distraction. Imagine a `list_of_enabled_documents` variable in the YAML. It contains the names of all the ALDocuments that should be enabled.
```python
list_of_enabled_documents = [ 'my_doc', 'next_steps' ]
```
That variable will _always_ have to be defined. Even if 'next_steps' becomes disabled, `list_of_enabled_documents` will still need to be there to contain 'my_doc'. Does that help make it more visible/explicit/discoverable than an attribute set in an object initialization? Harder to lose?

So that's an example of an alternative (unusable) interface that tries to deal with that problem (while creating others, of course). What are options that would actually be useable? What complications could they introduce?

**Comment by nonprofittechy** [comment]
> One option is to add defaults in the module when the objects are initialized, not in the YAML.

Whether a document is enabled or not is not something that you know when the interview is authored. It often depends on choices the user makes when running the interview. For example: in the 209A package, there are several optional documents that depend on whether the user has children.

Almost every court form should have optional documents, even if they don't yet:

* An Affidavit of Indigency
* An interpreter notice

So in our Assembly Line project, people will often need to understand if a document is enabled or not and set its value with code.

If we set a default value in the `init` method, there is now no way for Docassemble to seek a `code` block that provides the logic that determines if the document is needed or not. It doesn't matter how you set it in the Python code. To my knowledge, the only place that Docassemble will let you both seek a value and override a default dynamically is in the YAML.

> I'd be really interested in hearing more about what makes a generic object block more awkward.

The reason it is awkward to me: it is setting a class-wide default for a module in a separate file that doesn't usually contain core code. It is nice when things have a neat and clean interface. The YAML code also feels a bit hard to discover. I'll note that the ALDocument class does already require a YAML file to make the `send_email` functionality work. The virtue of that code though, is that it's something we don't expect people to interact with or override, and it's really a front-end concern since it is interacting with JavaScript.

Maybe something we can chat about on a Monday call. Using a `generic object` in the YAML would have the advantage of being a default that Docassemble knows how to ignore if there is a code block later in the file that overrides it. It could be helpful when we are migrating existing interviews from MAVC, but I am not sure how it would help a new developer in any other circumstance. The fact that a fair percentage of interviews--the most useful ones--will actually need to set the value to something other than the default pretty much cancels out any benefit in my mind.

Overall: people will either use the Weaver, use the function reference, or copy boilerplate code and modify it. Is it worth doing an unusual and hard to discover thing to remove one attribute from the list of required attributes? It just seems like it makes things more complex instead of simpler.

**Comment by BryceStevenWilley** [comment]
To summarize this discussion, I think we all agree that the example usage should be in the class docstring, and that we can consider more additions after that, though some of the above discussions don't seem technically possible in docassemble.

**Comment by nonprofittechy** [comment]
Thanks for reupping this. I think maybe the most helpful example is this, which I added to the readme.md earlier today:

> It is very common to have a contingent document in ALDocument. If your document is contingent, remove the enabled=True from the object declaration, and use some other method to "turn on" the attachment.
> E.g.,

```yaml
code: |
  CRA_Motion_to_Dismiss_attachment.enabled = condition1 and condition2
```

**Comment by plocket** [comment]
Just to note a clarification about the "list" - I specifically said I was giving an unusable example because I didn't want people to get hung up on that example. It's frustrating that the message didn't get through. Maybe we need to develop some vocabulary about how these types of concepts can be communicated.
